
if(CMAKE_CUDA_COMPILER)
  add_executable(saxpy-naive-cuda cuda/naive.cpp)
  set_source_files_properties(cuda/naive.cpp PROPERTIES LANGUAGE CUDA)
  set_target_properties(saxpy-naive-cuda PROPERTIES LINKER_LANGUAGE CUDA)
  target_link_libraries(saxpy-naive-cuda PUBLIC benchmark)
  target_include_directories(saxpy-naive-cuda PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/../common)
endif()

if(CMAKE_CUDA_COMPILER)
  add_executable(saxpy-optimized-cuda cuda/optimized.cpp)
  set_source_files_properties(cuda/optimized.cpp PROPERTIES LANGUAGE CUDA)
  set_target_properties(saxpy-optimized-cuda PROPERTIES LINKER_LANGUAGE CUDA)
  target_link_libraries(saxpy-optimized-cuda PUBLIC benchmark)
  target_include_directories(saxpy-optimized-cuda PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/../common)
endif()

if(SYCL_CUDA_AVAILABLE)
  add_executable(saxpy-naive-sycl sycl/naive.cpp)
  target_compile_options(saxpy-naive-sycl PRIVATE ${SYCL_CUDA_FLAGS})
  target_link_options(saxpy-naive-sycl PRIVATE ${SYCL_CUDA_FLAGS} -Wl,--disable-new-dtags)
  target_link_libraries(saxpy-naive-sycl PUBLIC benchmark)
endif()

if(SYCL_CUDA_AVAILABLE)
  add_executable(saxpy-optimized-sycl sycl/optimized.cpp)
  target_compile_options(saxpy-optimized-sycl PRIVATE ${SYCL_CUDA_FLAGS})
  target_link_options(saxpy-optimized-sycl PRIVATE ${SYCL_CUDA_FLAGS} -Wl,--disable-new-dtags)
  target_link_libraries(saxpy-optimized-sycl PUBLIC benchmark)
endif()
