
if(CMAKE_CUDA_COMPILER)
  add_executable(gemm-naive-cuda cuda/naive.cpp)
  set_source_files_properties(cuda/naive.cpp PROPERTIES LANGUAGE CUDA)
  set_target_properties(gemm-naive-cuda PROPERTIES LINKER_LANGUAGE CUDA)
  target_link_libraries(gemm-naive-cuda PUBLIC benchmark)
  target_include_directories(gemm-naive-cuda PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/../common)
endif()

# if(CMAKE_CUDA_COMPILER)
#   add_executable(gemm-optimized-cuda cuda/optimized.cpp)
#   set_source_files_properties(cuda/optimized.cpp PROPERTIES LANGUAGE CUDA)
#   set_target_properties(gemm-optimized-cuda PROPERTIES LINKER_LANGUAGE CUDA)
#   target_link_libraries(gemm-optimized-cuda PUBLIC benchmark)
#   target_include_directories(gemm-optimized-cuda PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/../common)
# endif()

if(SYCL_CUDA_AVAILABLE)
  add_executable(gemm-naive-sycl sycl/naive.cpp)
  target_compile_options(gemm-naive-sycl PRIVATE ${SYCL_CUDA_FLAGS})
  target_link_options(gemm-naive-sycl PRIVATE ${SYCL_CUDA_FLAGS} -Wl,--disable-new-dtags)
  target_link_libraries(gemm-naive-sycl PUBLIC benchmark)
endif()

if(SYCL_CUDA_AVAILABLE)
  add_executable(gemm-optimized-sycl sycl/optimized.cpp)
  target_compile_options(gemm-optimized-sycl PRIVATE ${SYCL_CUDA_FLAGS})
  target_link_options(gemm-optimized-sycl PRIVATE ${SYCL_CUDA_FLAGS} -Wl,--disable-new-dtags)
  target_link_libraries(gemm-optimized-sycl PUBLIC benchmark)
endif()
